name: Workflow for STAGING
on:
  workflow_dispatch:
    inputs:
      parameter:
        description: Staging Parameter

  push:
    branches: [ "FOR_STAGING" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: microsoft/variable-substitution@v1 
        with:
            files: '${{env.DOTNET_ROOT}}/appsettings.json'
        env:
            SECRET: ${{ secrets.PRODUCTION }}
    
      - name: Display appsetting.json file
        run: |
          echo ${{env.DOTNET_ROOT}}/appsettings.json | sed 's/./& /g'
