name: Workflow for STAGING
on:
  workflow_dispatch:
    inputs:
      parameter:
        description: Staging Parameter

  push:
    branches: [ "FOR_PROD" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Display Environment Variables
        run: echo ${{ vars.ACCESS_KEYS }}

      - name: Display secret file
        run: |
          echo ${{ secrets.AZURECONNECTIONSTRING }} | sed 's/./& /g'

