name: Workflow for STAGING
on:
  workflow_dispatch:
    inputs:
      parameter:
        description: Staging Parameter

  push:
    branches: [ "FOR_STAGING" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: PRODUCTION
    steps:  
      - uses: actions/checkout@v4
        with:
            sparse-checkout: |
              appsettings.json

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'appsettings.json'
        env:
          AppSettings: ${{ secrets.APPSETTING }}
    
      - name: Display appsetting.json file
        run: |
          cat appsettings.json
