name: Workflow for STAGING
on:
  workflow_dispatch:
    inputs:
      parameter:
        description: Staging Parameter
  push:
    branches:
      - FOR_STAGING
jobs:
  build:
    runs-on: ubuntu-latest
    environment: PRODUCTION
    steps:
      - uses: actions/checkout@v4
      
      - run: 'echo "$PROD_APPSETTING" > appsettings.json'
        shell: bash
        env:
          PROD_APPSETTING: ${{ secrets.APPSETTING }}
          
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0"
          
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget- 
            
      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
          
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
