name: Workflow for STAGING
on:
  workflow_dispatch:
    inputs:
      parameter:
        description: Staging Parameter

  push:
    branches: [ "FOR_STAGING" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: PRODUCTION
    steps:  
      - uses: actions/checkout@v4
        with:
            sparse-checkout: |
              appsettings.json
    
      - name: Display appsetting.json file
        run: |
          cat appsettings.json
          
      - name: Display secrets
        run: |
          echo ${{ secrets.AZURECONNECTIONSTRING }} | sed 's/./& /g'
